<a href="https://colab.research.google.com/github/SAGARNATH-S/Data_Analysis/blob/master/NumpyStatistical2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [8]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 
print(a)

[[30 65 70]
 [80 95 10]
 [50 90 60]]


In [10]:
print (np.median(a))

65.0


In [11]:
print (np.mean(a))

61.111111111111114


In [13]:
print (np.average(a))

61.111111111111114


In [14]:
print (np.percentile(a,50))

65.0
