<a href="https://colab.research.google.com/github/SAGARNATH-S/Data_Analysis/blob/master/NumpyFunctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np 

In [8]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
print(a) 
print (np.amin(a,1),"\n")
print (np.amin(a,0),"\n")
print (np.amax(a),"\n")
print (np.amax(a, axis = 0),"\n")

[[3 7 5]
 [8 4 3]
 [2 4 9]]
[3 3 2] 

[2 4 3] 

9 

[8 7 9] 

