<a href="https://colab.research.google.com/github/SAGARNATH-S/Data_Analysis/blob/master/NumpyMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy.matlib 
import numpy as np 

In [2]:
print (np.matlib.empty((2,2)))

[[5.e-324 5.e-324]
 [5.e-324 0.e+000]]


In [3]:
print (np.matlib.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [5]:
print (np.matlib.identity(3, dtype = float))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
i = np.matrix('1,2;3,4') 
print(i)

[[1 2]
 [3 4]]
