<a href="https://colab.research.google.com/github/SAGARNATH-S/Data_Analysis/blob/master/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**arange**

In [4]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**Zeros** and **Ones**

In [10]:
print(np.zeros((3,4)))
np.ones((3,4))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])