<a href="https://colab.research.google.com/github/SAGARNATH-S/Data_Analysis/blob/master/NumpyIO%26Hist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,3,4,5]) 
np.save('outfile',a)

In [3]:
b = np.load('outfile.npy') 
print(b)

[1 2 3 4 5]


In [5]:
a = np.array([22,87,5,43,56,73,55,54,11,20,51,5,79,31,27]) 
np.histogram(a,bins = [0,20,40,60,80,100]) 
hist,bins = np.histogram(a,bins = [0,20,40,60,80,100]) 
print (hist) 
print (bins)

[3 4 5 2 1]
[  0  20  40  60  80 100]
